version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: postgres
      POSTGRES_DB: controle-facil
    ports:
      - 5444:5432